version: '3.5'

services:
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: postgres:alpine3.17
    env_file:
      - .env
    ports:
      - "8080:8080"
    
    volumes:
      - ./dbdata:/db/data
    networks:
      - app-network
    restart: always

networks:
  app-network: